// GoldenCorpusTests — the determinism tripwire for classic generation.
//
// `PuzzleGenerator.generate(seed:difficulty:)` is a pure function, and the whole
// app leans on that: every daily is (day → seed) → puzzle, every shared board is
// a seed, and every stored `NineGame` carries the puzzle it was generated from.
// So a refactor of the solver, the dig-orbit shuffle, the RNG or the verifier
// that *quietly* changes the output is not a refactor — it silently re-rolls
// every daily and breaks every shared seed. GeneratorTests proves the invariants
// (unique, technique-bounded, symmetric); this file proves the *bytes*.
//
// Composition (50 pairs, full difficulty coverage) is cost-shaped, not uniform:
// generation costs ~0.03 s gentle, ~0.3 s steady, and 0.7–65 s sharp on the same
// machine, because sharp digs for maximal uniqueness and then heals back down.
// A uniform 17/17/16 split would cost several minutes on its own and blow the
// `swift test` < 120 s budget (DEVIATIONS.md, 10k-soak entry). So:
//   • gentle — seeds 1...30
//   • steady — seeds 1...14
//   • sharp  — six seeds picked out of a cost scan of 3000...3029 for being the
//     cheap ones (0.7–2.5 s each). They are as much a proof of the sharp path as
//     any others would be: same pipeline, same healing pass, frozen bytes.
// The list is written out explicitly below so it is frozen with the hashes.
//
// Re-freezing (only ever deliberately, see the failure message):
//   NINE_FREEZE_GOLDEN=1 swift test --filter GoldenCorpus 2>&1 | grep '^ *"'
import XCTest
import Foundation
@testable import NineEngine

final class GoldenCorpusTests: XCTestCase {

    /// The frozen corpus. Order is load-bearing — it indexes `frozenHashes`.
    static let corpus: [(seed: UInt64, difficulty: Difficulty)] = [
        (1, .gentle), (2, .gentle), (3, .gentle), (4, .gentle), (5, .gentle),
        (6, .gentle), (7, .gentle), (8, .gentle), (9, .gentle), (10, .gentle),
        (11, .gentle), (12, .gentle), (13, .gentle), (14, .gentle), (15, .gentle),
        (16, .gentle), (17, .gentle), (18, .gentle), (19, .gentle), (20, .gentle),
        (21, .gentle), (22, .gentle), (23, .gentle), (24, .gentle), (25, .gentle),
        (26, .gentle), (27, .gentle), (28, .gentle), (29, .gentle), (30, .gentle),
        (1, .steady), (2, .steady), (3, .steady), (4, .steady), (5, .steady),
        (6, .steady), (7, .steady), (8, .steady), (9, .steady), (10, .steady),
        (11, .steady), (12, .steady), (13, .steady), (14, .steady),
        (3002, .sharp), (3003, .sharp), (3007, .sharp),
        (3013, .sharp), (3015, .sharp), (3017, .sharp),
    ]

    /// SHA-256 of the canonical JSON encoding of each generated puzzle, in
    /// `corpus` order. GENERATED by running the freeze command in the header,
    /// never written by hand.
    static let frozenHashes: [String] = [
        "77ef90b5931f299a1dd5ab49b39e7d47e7a36d81138bba06ce35d1c1af431702", // 1 gentle
        "95bd714389bd3e24087da41af86ba3142f2663169d8e7141a4d4cfdd8de40b49", // 2 gentle
        "6fca651304a87dd3b450f8ba7321db2a101c1a9aa0baa908437a8325c71ab85a", // 3 gentle
        "e126b3770774ddb7ebba96761deff3926aadd69351c747ee19d31a2e971b408b", // 4 gentle
        "215a01f330a2560838eda82c6cb31d16ec2ec10ae1a70e8d778ace3173734e17", // 5 gentle
        "a1c370bc16a8cc93537d9eaa609bba027fa6703c92c6275e1ec866d0f0db92aa", // 6 gentle
        "cf20b693ba5788a74b1f8c71a85b9430a7913259a533cc2b2d31ae6916b9e2d3", // 7 gentle
        "afabd4240a4bb2c148ac3860894a68a65e2d998c1cb2ebf344f917fecfb1648b", // 8 gentle
        "a1e86eb20b6ce607cb5fca0e746277044e91ea0a08ea77fc0df8c40f2975070b", // 9 gentle
        "9016c750d55fb8adb50972038efcfe75a31f9f952a687af6f9bfcb8081a08e3e", // 10 gentle
        "e103d85eceb39b96408d0828dd12aa9a2d108318dd49656556b3e1d9871a6441", // 11 gentle
        "4f9e3ac284730ee73551966246892104f3e85dd66ed5e38d3741d076db2914f5", // 12 gentle
        "1490f55276b403b02147f356fdeef9bf0e7bccb46734f41ed71870be5aff1b37", // 13 gentle
        "7064e88a03faff98ae9821072e895126472b67e5e2dda669d0d409511307826d", // 14 gentle
        "2dbdc821db1175f526fb94eb2872406b45260b1d7e30926f2790fcc125fc44ac", // 15 gentle
        "04422c8955f0970429c913a8569078705dd3c32b80ace8d4ada9cc6e89c29976", // 16 gentle
        "bbe734aab4153839da24df0df1df6ec4a92694f47316f2b0d32f5a44d06af344", // 17 gentle
        "1c1531217419d19ba47259d4e23195adcd7d152f53c90966bf373e1a14d8ee66", // 18 gentle
        "7e423349f8155f9d1593c9be8684f3004bcfeef512a9dfbae3f9068ca7661dd3", // 19 gentle
        "9e5aeec68b4d3c7a64227df52e3d50e77e6a126c0175582cabccaaf8dd6af37c", // 20 gentle
        "0f95f86b10345642e48b72c7f43a45cbb3c091fc61a21d7d4221641b5c30fc27", // 21 gentle
        "d3d34e7ca17794216a060c364756f7f65c8b587fe65b62b012a6521de5669032", // 22 gentle
        "dda974105824f439f83f731ed5a4be743cc7a1430017fe55ec8ef27d6a639b69", // 23 gentle
        "c1781ee80d7757a1bced3828228eb7e166e8a4156ed775d160359798b2794f0d", // 24 gentle
        "dbe25cf98b3e2a90ecdb7d9b3072e311f77c766b6cab51ec6a5d4f7ce7417d8d", // 25 gentle
        "739bd45f0b0d15fb19dde0133b79df2751c45b51e9aac07013bb2f1b71cadec0", // 26 gentle
        "2f31759cbd6be27c2578b3860be04a45856d7a034665db5984b4a8d811765323", // 27 gentle
        "745de3aec203a3bbe0c305654b705fd88ff8433dd38b67fc893aed05917ad823", // 28 gentle
        "9a2469558717bc83356c764cee69df536487b0d4b7318e76d920c9678488b61c", // 29 gentle
        "a262a83b2e690cf24c86f4135824179c1dd5203154f1520625e81c8a2a223e51", // 30 gentle
        "342f336ccf34e6ad26d634e9936d775d4dda37a458ef81854af5903237da6e56", // 1 steady
        "b950080116e972d6b027ca5e145cce51f14fbf9b1db26a1726fa6c95894d4796", // 2 steady
        "908c89d51736ba096469465b05bde42f419c008354cff5e1d73148de84df16ff", // 3 steady
        "7d0899b81f9be1fb2eb9c43af00a76a5f2c72d7714e9ce793b3736ea255b02c9", // 4 steady
        "1ef0b55514d7ee44593f53212ebfb8b18902e9b643b51f970d6c13dc52d6784f", // 5 steady
        "398213ca09dfc45794fae84bffbbde0b3b225f342e6871ccbc86fd999cc2ca8a", // 6 steady
        "dabad4c41e55712a646dab527cfa0448497c9d722822937f9ecc8191bee5a4d2", // 7 steady
        "48f26280a0ac55e71b0e7577fa7ef8d025fdc66e287199e6b58f006c4d5e60e5", // 8 steady
        "92325dbe422024508e7ffe1283945eb8d38c26aae6ff693d63ff7f0210c8f1e6", // 9 steady
        "197e48312b2203e5c55260409e2a6da0c5a16468d219752d04ba34991765c5b3", // 10 steady
        "18a4deae8e081a3c9894a742f974af926dbe60eda503606578f147fc2b81e4e6", // 11 steady
        "839e82c2671116d86439d7d5cc1face286f1794161f66cc8e151fe0241bca626", // 12 steady
        "7317d40a8363222a2cb15f3fa6ce30cc8624432595ff1dede815c4d7f1539a36", // 13 steady
        "8849b023151134c7abebed18e00b3889aa8302698af61f7b4047776038cdf86d", // 14 steady
        "6e58550b569ebe70279ff7dd082998b90ef1c663286631cafa8b1daa4ff8cf68", // 3002 sharp
        "82aebc535f567a60487178f2d4309d0466bcc9b213fdd53c8b9c5d7628d5f01e", // 3003 sharp
        "3e907e2c485987ae556928a6be6b2ccf67a08dc0449b7b0eac16160cf9cd3ba3", // 3007 sharp
        "9d4ecf31cfc3909cc6e96cc4f2c1ec226b551e6e523340f52d09efe90017e102", // 3013 sharp
        "a7a9a8643cd5f14b6cf8fac3f421500dcbfa8def0b080721cf6fbdca6fdfbce3", // 3015 sharp
        "3c79792eb5bcdf4e0f781d51f76b8918758971a9c38884aa2116b6ccb0a5248f", // 3017 sharp
    ]

    /// What a mismatch means, spelled out at the failure site: this is the one
    /// assertion in the suite that a well-meaning refactor will trip.
    private static let covenant = """
        classic generation changed — every future daily and every shared seed \
        just moved. A stored board still replays (the puzzle travels inside the \
        save), but the same seed no longer yields the same puzzle, so two \
        devices on the same day now disagree. If this was intentional, \
        re-freeze deliberately: NINE_FREEZE_GOLDEN=1 swift test --filter \
        GoldenCorpus
        """

    // MARK: - The tripwire

    func testClassicGenerationMatchesTheFrozenCorpus() throws {
        if ProcessInfo.processInfo.environment["NINE_FREEZE_GOLDEN"] != nil {
            try freeze()
            return
        }
        XCTAssertEqual(Self.corpus.count, Self.frozenHashes.count,
                       "corpus and frozen hashes are out of step — re-freeze")
        for (index, pair) in Self.corpus.enumerated() {
            let hash = try Self.hash(seed: pair.seed, difficulty: pair.difficulty)
            XCTAssertEqual(hash, Self.frozenHashes[index],
                           "seed \(pair.seed) / \(pair.difficulty): \(Self.covenant)")
        }
    }

    /// The corpus is only a tripwire if the hasher itself is trustworthy, so pin
    /// it to the FIPS 180-4 vectors. A failure here means the hash function
    /// changed, not the generator.
    func testSHA256MatchesTheStandardVectors() {
        XCTAssertEqual(SHA256Lite.hex(Data()),
                       "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
        XCTAssertEqual(SHA256Lite.hex(Data("abc".utf8)),
                       "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
        XCTAssertEqual(
            SHA256Lite.hex(Data("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq".utf8)),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1")
        // Crosses the 64-byte block boundary (two blocks + padding).
        XCTAssertEqual(SHA256Lite.hex(Data(String(repeating: "a", count: 1_000_000).utf8)),
                       "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0")
    }

    // MARK: - Hashing

    /// Canonical bytes for a generated puzzle. `.sortedKeys` rather than
    /// `CouchJSON` on purpose: the hash must not move if the persistence layer
    /// ever changes its formatting, and `GeneratedPuzzle` holds no `Date`, so no
    /// date strategy participates. Everything in it — grids, difficulty, seed
    /// and the full `SolveStep` trace — is inside the hash, which is the point:
    /// a solver change that alters the *explanation* while still solving the
    /// board is exactly the kind of drift this catches.
    static func hash(seed: UInt64, difficulty: Difficulty) throws -> String {
        let puzzle = PuzzleGenerator.generate(seed: seed, difficulty: difficulty)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        return SHA256Lite.hex(try encoder.encode(puzzle))
    }

    /// Print a paste-ready `frozenHashes` literal. Deliberately not a test of
    /// its own — re-freezing is an edit, and it should read like one.
    private func freeze() throws {
        var lines: [String] = []
        for pair in Self.corpus {
            let started = Date()
            let hash = try Self.hash(seed: pair.seed, difficulty: pair.difficulty)
            lines.append(#"        "\#(hash)", // \#(pair.seed) \#(pair.difficulty)"#)
            FileHandle.standardError.write(Data(
                "freeze \(pair.difficulty) \(pair.seed) \(Date().timeIntervalSince(started))s\n".utf8))
        }
        print(lines.joined(separator: "\n"))
    }
}

// MARK: - SHA-256

/// Minimal SHA-256 (FIPS 180-4), self-contained on purpose.
///
/// CryptoKit does not exist on Linux and CI Lane 1 is Linux SwiftPM, so the
/// usual `#if canImport(CryptoKit)` / `import Crypto` shim would mean taking
/// swift-crypto as a package dependency — a transitive dependency on the whole
/// engine (and on every app target that compiles it in) in exchange for hashing
/// 50 small JSON blobs in one test. Forty lines of well-pinned arithmetic is the
/// cheaper trade. `testSHA256MatchesTheStandardVectors` guards it.
enum SHA256Lite {

    static func hex(_ data: Data) -> String {
        var h: [UInt32] = [
            0x6a09_e667, 0xbb67_ae85, 0x3c6e_f372, 0xa54f_f53a,
            0x510e_527f, 0x9b05_688c, 0x1f83_d9ab, 0x5be0_cd19,
        ]
        var message = [UInt8](data)
        let bitCount = UInt64(message.count) &* 8
        message.append(0x80)
        while message.count % 64 != 56 { message.append(0) }
        for shift in stride(from: 56, through: 0, by: -8) {
            message.append(UInt8(truncatingIfNeeded: bitCount >> UInt64(shift)))
        }

        var w = [UInt32](repeating: 0, count: 64)
        for base in stride(from: 0, to: message.count, by: 64) {
            for i in 0..<16 {
                let j = base + i * 4
                w[i] = UInt32(message[j]) << 24 | UInt32(message[j + 1]) << 16
                     | UInt32(message[j + 2]) << 8 | UInt32(message[j + 3])
            }
            for i in 16..<64 {
                let s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >> 3)
                let s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >> 10)
                w[i] = w[i - 16] &+ s0 &+ w[i - 7] &+ s1
            }
            var (a, b, c, d) = (h[0], h[1], h[2], h[3])
            var (e, f, g, hh) = (h[4], h[5], h[6], h[7])
            for i in 0..<64 {
                let s1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)
                let ch = (e & f) ^ (~e & g)
                let t1 = hh &+ s1 &+ ch &+ k[i] &+ w[i]
                let s0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)
                let maj = (a & b) ^ (a & c) ^ (b & c)
                let t2 = s0 &+ maj
                (hh, g, f, e) = (g, f, e, d &+ t1)
                (d, c, b, a) = (c, b, a, t1 &+ t2)
            }
            let round = [a, b, c, d, e, f, g, hh]
            for i in 0..<8 { h[i] = h[i] &+ round[i] }
        }
        return h.map { String(format: "%08x", $0) }.joined()
    }

    private static func rotr(_ x: UInt32, _ n: UInt32) -> UInt32 {
        (x >> n) | (x << (32 - n))
    }

    /// The first 32 bits of the fractional parts of the cube roots of the first
    /// 64 primes (FIPS 180-4 §4.2.2).
    private static let k: [UInt32] = [
        0x428a_2f98, 0x7137_4491, 0xb5c0_fbcf, 0xe9b5_dba5,
        0x3956_c25b, 0x59f1_11f1, 0x923f_82a4, 0xab1c_5ed5,
        0xd807_aa98, 0x1283_5b01, 0x2431_85be, 0x550c_7dc3,
        0x72be_5d74, 0x80de_b1fe, 0x9bdc_06a7, 0xc19b_f174,
        0xe49b_69c1, 0xefbe_4786, 0x0fc1_9dc6, 0x240c_a1cc,
        0x2de9_2c6f, 0x4a74_84aa, 0x5cb0_a9dc, 0x76f9_88da,
        0x983e_5152, 0xa831_c66d, 0xb003_27c8, 0xbf59_7fc7,
        0xc6e0_0bf3, 0xd5a7_9147, 0x06ca_6351, 0x1429_2967,
        0x27b7_0a85, 0x2e1b_2138, 0x4d2c_6dfc, 0x5338_0d13,
        0x650a_7354, 0x766a_0abb, 0x81c2_c92e, 0x9272_2c85,
        0xa2bf_e8a1, 0xa81a_664b, 0xc24b_8b70, 0xc76c_51a3,
        0xd192_e819, 0xd699_0624, 0xf40e_3585, 0x106a_a070,
        0x19a4_c116, 0x1e37_6c08, 0x2748_774c, 0x34b0_bcb5,
        0x391c_0cb3, 0x4ed8_aa4a, 0x5b9c_ca4f, 0x682e_6ff3,
        0x748f_82ee, 0x78a5_636f, 0x84c8_7814, 0x8cc7_0208,
        0x90be_fffa, 0xa450_6ceb, 0xbef9_a3f7, 0xc671_78f2,
    ]
}
