// VariantCorpusTests — the determinism tripwire for variant generation, and the
// bill that comes due the moment a channel has a daily.
//
// PRD-23 shipped variant generation with no corpus, and that was correct: nothing
// was persisted, no daily depended on it, so nothing downstream could break if it
// moved. **PRD-24 changes that in one line of product spec.** "Dailies one per day
// per channel" means every channel daily is `(day → seed) → board`, so a quiet
// change to `CageTiling`, `ThermoTiling`, the band ladder, the inverse dig, the
// trim or the verifier re-rolls every future channel daily and breaks every shared
// channel seed — the identical hazard `GoldenCorpusTests` exists for, one ruleset
// over.
//
// So variant generation is now frozen, exactly as classic is, and the same rules
// apply: a mismatch is a bug until proven otherwise, and re-freezing is a
// deliberate act with a paper trail.
//
//     NINE_FREEZE_VARIANT_CORPUS=1 swift test --filter VariantCorpus 2>&1 | grep '^ *"'
//
// Composition is cost-shaped, not uniform, for the reason the classic corpus
// states: **`swift test` builds Debug and generation runs ~50× slower there**
// (measured, PRD-17: 0.428 s release against 30.8 s debug). Thermo's Release p95
// is 0.01–0.03 s and killer's is 0.02–0.14 s, so a Debug seed costs roughly
// 0.5–7 s. Six thermo seeds and three killer seeds is what fits beside the
// classic corpus's own 25 s inside the suite budget; every one of them runs the
// full pipeline, which is what makes them a proof rather than a sample.
import XCTest
import Foundation
@testable import NineEngine

final class VariantCorpusTests: XCTestCase {

    /// The frozen corpus. Order is load-bearing — it indexes `frozenHashes`.
    ///
    /// Thermo carries the weight because thermo ships first and is cheap; killer
    /// gets one seed per tier, which is enough to catch a change to the shared dig,
    /// trim and verifier (all three are the *same code* thermo runs) plus one to
    /// `CageTiling` specifically. Sharp killer is the expensive one and it is
    /// included anyway: it is the zero-given tier, so it is the one with no givens
    /// to mask a drift.
    static let corpus: [(seed: UInt64, variant: Variant, tier: VariantTier)] = [
        (1, .thermo, .gentle), (2, .thermo, .gentle),
        (1, .thermo, .steady), (2, .thermo, .steady),
        (1, .thermo, .sharp), (2, .thermo, .sharp),
        (1, .killer, .gentle),
        (1, .killer, .steady),
        (1, .killer, .sharp),
    ]

    /// SHA-256 of the canonical JSON encoding of each composed board, in `corpus`
    /// order. GENERATED by running the freeze command in the header, never written
    /// by hand.
    static let frozenHashes: [String] = [
        "8f2f1480de2c3b4f06d647d265ad11a8f271b88ee7ded945d690a1d0dbc3d1e8", // 1 thermo gentle
        "261850777ac57dab7c1714a9dada877cddea7d058c1e5ea16ff7b5530b46a645", // 2 thermo gentle
        "88a3ebd4d39a96b1a9a7c472cfaf0e80fbd00bde9eccbab646fd4f264066d81b", // 1 thermo steady
        "d4849d1938d65c2a4c720def6694e8845aca376ac35b17451e6bfdb2ca2911ae", // 2 thermo steady
        "f18f3cce2c3fe0f655619758e3a758322adc3769b39e354e50d720030ccf0b2e", // 1 thermo sharp
        "3543abb2c28eab160f4724d3ab041a91cd88960af199b2e578d0794e1196b3e3", // 2 thermo sharp
        "089d3d8fb02487ab9346e990a958511dcc1b848b984da1146b3b6e2174e83c42", // 1 killer gentle
        "80169489a138d8ecc05734a342a6789a63454b7fd61b11bf4f76fe05fcdb0762", // 1 killer steady
        "60f6d0aa76a90e20c57b5d6c53cf2dbcf2651a690075443c6bb7ab3d4671d48a", // 1 killer sharp
    ]

    /// What a mismatch means, spelled out at the failure site.
    private static let covenant = """
        variant generation changed — every future channel daily and every shared \
        channel seed just moved. A stored board still replays (the puzzle and its \
        rules both travel inside the save, `ChannelRules`), but the same seed no \
        longer yields the same board, so two devices on the same day now \
        disagree about the Thermo or Killer daily. If this was intentional, \
        re-freeze deliberately: NINE_FREEZE_VARIANT_CORPUS=1 swift test --filter \
        VariantCorpus
        """

    // MARK: - The tripwire

    func testVariantGenerationMatchesTheFrozenCorpus() throws {
        if ProcessInfo.processInfo.environment["NINE_FREEZE_VARIANT_CORPUS"] != nil {
            try freeze()
            return
        }
        XCTAssertEqual(Self.corpus.count, Self.frozenHashes.count,
                       "corpus and frozen hashes are out of step — re-freeze")
        for (index, item) in Self.corpus.enumerated() {
            let hash = try Self.hash(seed: item.seed, variant: item.variant, tier: item.tier)
            XCTAssertEqual(
                hash, Self.frozenHashes[index],
                "seed \(item.seed) / \(item.variant.rawValue) \(item.tier): \(Self.covenant)")
        }
    }

    /// A channel daily has to be the same board on two devices, which is a
    /// stronger claim than "generation is deterministic": it also requires that
    /// the *day* is the only input that varies, and that two channels never hand
    /// out the same board on the same day.
    func testAChannelDailyIsAPureFunctionOfItsDayAndChannel() throws {
        let day = 20_649
        let seed = DailySeed.seed(forDayOrdinal: day)
        let thermo = try XCTUnwrap(
            VariantGenerator.generate(seed: seed, variant: .thermo, tier: .steady))
        let again = try XCTUnwrap(
            VariantGenerator.generate(seed: seed, variant: .thermo, tier: .steady))
        XCTAssertEqual(thermo, again, "the same day must be the same board")

        // A different day is a different board.
        let tomorrow = try XCTUnwrap(VariantGenerator.generate(
            seed: DailySeed.seed(forDayOrdinal: day + 1), variant: .thermo, tier: .steady))
        XCTAssertNotEqual(thermo.puzzle, tomorrow.puzzle)

        // And the channels do not collide on the same day. `Variant.seedSalt` is
        // what guarantees this, and it is an explicit constant rather than a
        // `hashValue` precisely so it cannot move between launches.
        let killer = try XCTUnwrap(
            VariantGenerator.generate(seed: seed, variant: .killer, tier: .steady))
        XCTAssertNotEqual(thermo.puzzle, killer.puzzle,
                          "two channels must not share a day's board")
        XCTAssertNotEqual(thermo.solution, killer.solution)
    }

    // MARK: - Hashing

    /// Canonical bytes for a composed variant board. `.sortedKeys` rather than
    /// `CouchJSON`, for `GoldenCorpusTests.hash`'s reason: the hash must not move
    /// if the persistence layer changes its formatting, and `VariantPuzzle` holds
    /// no `Date`.
    ///
    /// Everything is inside the hash — the constraints, the grid, the solution,
    /// the seed, the tier and the full `SolveStep` trace — which is the point. A
    /// change that alters the *explanation* while still solving the board is
    /// exactly the drift this catches, and for a variant the explanation is what
    /// the coach reads out.
    static func hash(seed: UInt64, variant: Variant, tier: VariantTier) throws -> String {
        let puzzle = try XCTUnwrap(
            VariantGenerator.generate(seed: seed, variant: variant, tier: tier),
            "\(variant.rawValue) \(tier) seed \(seed) did not compose — a corpus seed must")
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        return SHA256Lite.hex(try encoder.encode(puzzle))
    }

    /// Print a paste-ready `frozenHashes` literal. Deliberately not a test of its
    /// own — re-freezing is an edit, and it should read like one.
    private func freeze() throws {
        var lines: [String] = []
        for item in Self.corpus {
            let started = Date()
            let hash = try Self.hash(seed: item.seed, variant: item.variant, tier: item.tier)
            lines.append(
                #"        "\#(hash)", // \#(item.seed) \#(item.variant.rawValue) \#(item.tier)"#)
            let elapsed = Date().timeIntervalSince(started)
            FileHandle.standardError.write(Data(
                "freeze \(item.variant.rawValue) \(item.tier) \(item.seed) \(elapsed)s\n".utf8))
        }
        print(lines.joined(separator: "\n"))
    }
}
