// General knowledge — 32 questions (12 warm, 12 medium, 8 hard).
// Correct slots cycle 0→1→2→3 to keep direction balance exact.
import Foundation

enum PackGeneral {
    static let questions: [Question] = [
        // Difficulty 1 — warm-ups
        packQuestion("gen-01", "How many days are in a leap year?",
                     correct: "366", wrong: ["365", "364", "360"],
                     slot: 0, .general, 1),
        packQuestion("gen-02", "Mixing blue and yellow paint makes which color?",
                     correct: "Green", wrong: ["Purple", "Orange", "Brown"],
                     slot: 1, .general, 1),
        packQuestion("gen-03", "How many sides does a hexagon have?",
                     correct: "Six", wrong: ["Five", "Seven", "Eight"],
                     slot: 2, .general, 1),
        packQuestion("gen-04", "Which meal traditionally starts the day?",
                     correct: "Breakfast", wrong: ["Lunch", "Dinner", "Supper"],
                     slot: 3, .general, 1),
        packQuestion("gen-05", "How many minutes are in one hour?",
                     correct: "Sixty", wrong: ["Fifty", "Ninety", "One hundred"],
                     slot: 0, .general, 1),
        packQuestion("gen-06", "What do honeybees make?",
                     correct: "Honey", wrong: ["Butter", "Syrup", "Jam"],
                     slot: 1, .general, 1),
        packQuestion("gen-07", "How many legs does a spider have?",
                     correct: "Eight", wrong: ["Six", "Ten", "Twelve"],
                     slot: 2, .general, 1),
        packQuestion("gen-08", "Which season follows winter?",
                     correct: "Spring", wrong: ["Summer", "Autumn", "Rainy season"],
                     slot: 3, .general, 1),
        packQuestion("gen-09", "How many cards are in a standard deck, jokers aside?",
                     correct: "52", wrong: ["48", "54", "60"],
                     slot: 0, .general, 1),
        packQuestion("gen-10", "What is frozen water called?",
                     correct: "Ice", wrong: ["Steam", "Mist", "Vapor"],
                     slot: 1, .general, 1),
        packQuestion("gen-11", "How many strings does a standard guitar have?",
                     correct: "Six", wrong: ["Four", "Five", "Eight"],
                     slot: 2, .general, 1),
        packQuestion("gen-12", "Which direction does a compass needle point?",
                     correct: "North", wrong: ["South", "East", "West"],
                     slot: 3, .general, 1),

        // Difficulty 2
        packQuestion("gen-13", "Which metal is liquid at room temperature?",
                     correct: "Mercury", wrong: ["Copper", "Aluminum", "Lead"],
                     slot: 0, .general, 2),
        packQuestion("gen-14", "How many squares are on a chessboard?",
                     correct: "64", wrong: ["49", "72", "81"],
                     slot: 1, .general, 2),
        packQuestion("gen-15", "What currency is used in Japan?",
                     correct: "Yen", wrong: ["Won", "Yuan", "Baht"],
                     slot: 2, .general, 2),
        packQuestion("gen-16", "Which blood type is the universal donor?",
                     correct: "O negative", wrong: ["AB positive", "A negative", "B positive"],
                     slot: 3, .general, 2),
        packQuestion("gen-17", "How many bones are in an adult human body?",
                     correct: "206", wrong: ["186", "226", "300"],
                     slot: 0, .general, 2),
        packQuestion("gen-18", "In which sport do players perform a slam dunk?",
                     correct: "Basketball", wrong: ["Volleyball", "Tennis", "Handball"],
                     slot: 1, .general, 2),
        packQuestion("gen-19", "What is a group of lions called?",
                     correct: "A pride", wrong: ["A pack", "A herd", "A troop"],
                     slot: 2, .general, 2),
        packQuestion("gen-20", "Which month is named after Julius Caesar?",
                     correct: "July", wrong: ["June", "August", "March"],
                     slot: 3, .general, 2),
        packQuestion("gen-21", "How many soccer players per team are on the field?",
                     correct: "Eleven", wrong: ["Nine", "Ten", "Twelve"],
                     slot: 0, .general, 2),
        packQuestion("gen-22", "What is the tallest living animal?",
                     correct: "Giraffe", wrong: ["Elephant", "Ostrich", "Moose"],
                     slot: 1, .general, 2),
        packQuestion("gen-23", "Which chess piece moves only diagonally?",
                     correct: "Bishop", wrong: ["Rook", "Knight", "Queen"],
                     slot: 2, .general, 2),
        packQuestion("gen-24", "How many time zones does China officially use?",
                     correct: "One", wrong: ["Three", "Five", "Seven"],
                     slot: 3, .general, 2),

        // Difficulty 3
        packQuestion("gen-25", "Which ancient wonder stood at Alexandria?",
                     correct: "The Lighthouse", wrong: ["The Colossus", "Hanging Gardens", "The Great Pyramid"],
                     slot: 0, .general, 3),
        packQuestion("gen-26", "In which year did the Berlin Wall fall?",
                     correct: "1989", wrong: ["1985", "1991", "1993"],
                     slot: 1, .general, 3),
        packQuestion("gen-27", "Which Roman numeral means 900?",
                     correct: "CM", wrong: ["MC", "DCC", "XM"],
                     slot: 2, .general, 3),
        packQuestion("gen-28", "How many points is the letter Q worth in Scrabble?",
                     correct: "Ten", wrong: ["Four", "Eight", "Twelve"],
                     slot: 3, .general, 3),
        packQuestion("gen-29", "Which country has the longest coastline?",
                     correct: "Canada", wrong: ["Russia", "Australia", "Indonesia"],
                     slot: 0, .general, 3),
        packQuestion("gen-30", "What was the first toy advertised on American TV?",
                     correct: "Mr. Potato Head", wrong: ["Barbie", "Hula hoop", "Slinky"],
                     slot: 1, .general, 3),
        packQuestion("gen-31", "How many dots are on a standard die in total?",
                     correct: "21", wrong: ["18", "24", "27"],
                     slot: 2, .general, 3),
        packQuestion("gen-32", "In which decade was the first email sent?",
                     correct: "1970s", wrong: ["1960s", "1980s", "1990s"],
                     slot: 3, .general, 3),
    ]
}
