// Odd One Out — 24 questions (12 medium, 12 hard). The prompt names the
// shared property; knowing which item breaks it is the puzzle.
// Correct slots cycle 0→1→2→3 to keep direction balance exact.
import Foundation

enum PackOddOneOut {
    static let questions: [Question] = [
        // Difficulty 2
        packQuestion("odd-01", "Odd one out: which of these is not a planet?",
                     correct: "Europa", wrong: ["Mercury", "Venus", "Mars"],
                     slot: 0, .oddOneOut, 2),
        packQuestion("odd-02", "Odd one out: which is not a fish?",
                     correct: "Dolphin", wrong: ["Salmon", "Trout", "Tuna"],
                     slot: 1, .oddOneOut, 2),
        packQuestion("odd-03", "Odd one out: which is not a string instrument?",
                     correct: "Trumpet", wrong: ["Violin", "Cello", "Viola"],
                     slot: 2, .oddOneOut, 2),
        packQuestion("odd-04", "Odd one out: which is not a capital city?",
                     correct: "Sydney", wrong: ["Paris", "Berlin", "Madrid"],
                     slot: 3, .oddOneOut, 2),
        packQuestion("odd-05", "Odd one out: which is not a tree?",
                     correct: "Rose", wrong: ["Oak", "Maple", "Pine"],
                     slot: 0, .oddOneOut, 2),
        packQuestion("odd-06", "Odd one out: which is not a metal?",
                     correct: "Oxygen", wrong: ["Copper", "Iron", "Gold"],
                     slot: 1, .oddOneOut, 2),
        packQuestion("odd-07", "Odd one out: which shape has no corners?",
                     correct: "Circle", wrong: ["Square", "Triangle", "Pentagon"],
                     slot: 2, .oddOneOut, 2),
        packQuestion("odd-08", "Odd one out: which is not a bird?",
                     correct: "Bat", wrong: ["Eagle", "Sparrow", "Owl"],
                     slot: 3, .oddOneOut, 2),
        packQuestion("odd-09", "Odd one out: which is not a Romance language?",
                     correct: "German", wrong: ["Spanish", "French", "Italian"],
                     slot: 0, .oddOneOut, 2),
        packQuestion("odd-10", "Odd one out: which is not a river?",
                     correct: "Sahara", wrong: ["Nile", "Amazon", "Danube"],
                     slot: 1, .oddOneOut, 2),
        packQuestion("odd-11", "Odd one out: which is not a chemical element?",
                     correct: "Bronze", wrong: ["Mercury", "Silver", "Copper"],
                     slot: 2, .oddOneOut, 2),
        packQuestion("odd-12", "Odd one out: which is not a swimming stroke?",
                     correct: "Slalom", wrong: ["Breaststroke", "Butterfly", "Freestyle"],
                     slot: 3, .oddOneOut, 2),

        // Difficulty 3
        packQuestion("odd-13", "Odd one out: which of these lays eggs?",
                     correct: "Platypus", wrong: ["Kangaroo", "Koala", "Wombat"],
                     slot: 0, .oddOneOut, 3),
        packQuestion("odd-14", "Odd one out: which was not a composer?",
                     correct: "Picasso", wrong: ["Mozart", "Beethoven", "Bach"],
                     slot: 1, .oddOneOut, 3),
        packQuestion("odd-15", "Odd one out: which city is not a national capital?",
                     correct: "Shanghai", wrong: ["Tokyo", "Seoul", "Bangkok"],
                     slot: 2, .oddOneOut, 3),
        packQuestion("odd-16", "Odd one out: which is not a noble gas?",
                     correct: "Chlorine", wrong: ["Helium", "Neon", "Argon"],
                     slot: 3, .oddOneOut, 3),
        packQuestion("odd-17", "Odd one out: which planet is not a giant?",
                     correct: "Mars", wrong: ["Jupiter", "Saturn", "Neptune"],
                     slot: 0, .oddOneOut, 3),
        packQuestion("odd-18", "Odd one out: which bone is in the arm?",
                     correct: "Ulna", wrong: ["Femur", "Tibia", "Fibula"],
                     slot: 1, .oddOneOut, 3),
        packQuestion("odd-19", "Odd one out: which is not a cloud type?",
                     correct: "Tundra", wrong: ["Cirrus", "Cumulus", "Stratus"],
                     slot: 2, .oddOneOut, 3),
        packQuestion("odd-20", "Odd one out: which currency is not Asian?",
                     correct: "Zloty", wrong: ["Baht", "Yen", "Won"],
                     slot: 3, .oddOneOut, 3),
        packQuestion("odd-21", "Odd one out: which mission carried no astronauts?",
                     correct: "Voyager", wrong: ["Mercury", "Apollo", "Gemini"],
                     slot: 0, .oddOneOut, 3),
        packQuestion("odd-22", "Odd one out: which is not a form of poem?",
                     correct: "Fresco", wrong: ["Sonnet", "Haiku", "Limerick"],
                     slot: 1, .oddOneOut, 3),
        packQuestion("odd-23", "Odd one out: which is not an ocean?",
                     correct: "Caspian", wrong: ["Atlantic", "Pacific", "Arctic"],
                     slot: 2, .oddOneOut, 3),
        packQuestion("odd-24", "Odd one out: which is not a cat?",
                     correct: "Hyena", wrong: ["Leopard", "Cheetah", "Jaguar"],
                     slot: 3, .oddOneOut, 3),
    ]
}
