// Movies & music — 28 questions (10 warm, 10 medium, 8 hard).
// Correct slots cycle 0→1→2→3 to keep direction balance exact.
import Foundation

enum PackScreen {
    static let questions: [Question] = [
        // Difficulty 1 — warm-ups
        packQuestion("scr-01", "Which instrument has 88 keys?",
                     correct: "The piano", wrong: ["The organ", "The harp", "The accordion"],
                     slot: 0, .screen, 1),
        packQuestion("scr-02", "In \"The Lion King\", what animal is Simba?",
                     correct: "A lion", wrong: ["A tiger", "A leopard", "A cheetah"],
                     slot: 1, .screen, 1),
        packQuestion("scr-03", "The trumpet belongs to which instrument family?",
                     correct: "Brass", wrong: ["Strings", "Woodwind", "Percussion"],
                     slot: 2, .screen, 1),
        packQuestion("scr-04", "How many strings does a violin have?",
                     correct: "Four", wrong: ["Three", "Five", "Six"],
                     slot: 3, .screen, 1),
        packQuestion("scr-05", "Which film stars a clownfish named Nemo?",
                     correct: "Finding Nemo", wrong: ["Shark Tale", "The Little Mermaid", "Moana"],
                     slot: 0, .screen, 1),
        packQuestion("scr-06", "What kind of creature is Shrek?",
                     correct: "An ogre", wrong: ["A troll", "A giant", "A goblin"],
                     slot: 1, .screen, 1),
        packQuestion("scr-07", "Who is called the King of Pop?",
                     correct: "Michael Jackson", wrong: ["Elvis Presley", "Prince", "Freddie Mercury"],
                     slot: 2, .screen, 1),
        packQuestion("scr-08", "In \"Toy Story\", what kind of doll is Woody?",
                     correct: "A cowboy", wrong: ["A spaceman", "A pirate", "A knight"],
                     slot: 3, .screen, 1),
        packQuestion("scr-09", "Which wizard studies at Hogwarts?",
                     correct: "Harry Potter", wrong: ["Gandalf", "Merlin", "Bilbo Baggins"],
                     slot: 0, .screen, 1),
        packQuestion("scr-10", "How many musicians play in a quartet?",
                     correct: "Four", wrong: ["Two", "Three", "Five"],
                     slot: 1, .screen, 1),

        // Difficulty 2
        packQuestion("scr-11", "Who composed the \"Moonlight Sonata\"?",
                     correct: "Beethoven", wrong: ["Mozart", "Chopin", "Bach"],
                     slot: 2, .screen, 2),
        packQuestion("scr-12", "In \"Star Wars\", who is Luke Skywalker's father?",
                     correct: "Darth Vader", wrong: ["Obi-Wan Kenobi", "Emperor Palpatine", "Han Solo"],
                     slot: 3, .screen, 2),
        packQuestion("scr-13", "Which band recorded \"Hey Jude\"?",
                     correct: "The Beatles", wrong: ["The Rolling Stones", "The Beach Boys", "The Kinks"],
                     slot: 0, .screen, 2),
        packQuestion("scr-14", "What is the highest female singing voice?",
                     correct: "Soprano", wrong: ["Alto", "Mezzo", "Contralto"],
                     slot: 1, .screen, 2),
        packQuestion("scr-15", "How many notes span an octave, counting both ends?",
                     correct: "Eight", wrong: ["Six", "Seven", "Ten"],
                     slot: 2, .screen, 2),
        packQuestion("scr-16", "In \"The Wizard of Oz\", what is Dorothy's dog called?",
                     correct: "Toto", wrong: ["Rex", "Buddy", "Sparky"],
                     slot: 3, .screen, 2),
        packQuestion("scr-17", "Which country is the band ABBA from?",
                     correct: "Sweden", wrong: ["Norway", "Denmark", "Germany"],
                     slot: 0, .screen, 2),
        packQuestion("scr-18", "Who directed both \"Jaws\" and \"E.T.\"?",
                     correct: "Steven Spielberg", wrong: ["George Lucas", "James Cameron", "Ridley Scott"],
                     slot: 1, .screen, 2),
        packQuestion("scr-19", "Which film made \"I'll be back\" famous?",
                     correct: "The Terminator", wrong: ["Die Hard", "RoboCop", "Rambo"],
                     slot: 2, .screen, 2),
        packQuestion("scr-20", "Which instrument did Louis Armstrong play?",
                     correct: "The trumpet", wrong: ["The saxophone", "The clarinet", "The trombone"],
                     slot: 3, .screen, 2),

        // Difficulty 3
        packQuestion("scr-21", "Which film won the very first Best Picture Oscar?",
                     correct: "Wings", wrong: ["Sunrise", "Metropolis", "The Jazz Singer"],
                     slot: 0, .screen, 3),
        packQuestion("scr-22", "Who composed \"The Four Seasons\"?",
                     correct: "Vivaldi", wrong: ["Handel", "Haydn", "Brahms"],
                     slot: 1, .screen, 3),
        packQuestion("scr-23", "In music, what does \"fortissimo\" mean?",
                     correct: "Very loud", wrong: ["Very fast", "Very soft", "Very slow"],
                     slot: 2, .screen, 3),
        packQuestion("scr-24", "Which 1941 film is famed for the sled \"Rosebud\"?",
                     correct: "Citizen Kane", wrong: ["Casablanca", "Rebecca", "The Third Man"],
                     slot: 3, .screen, 3),
        packQuestion("scr-25", "Which film introduced \"The Imperial March\"?",
                     correct: "The Empire Strikes Back", wrong: ["A New Hope", "Return of the Jedi", "The Phantom Menace"],
                     slot: 0, .screen, 3),
        packQuestion("scr-26", "Which musical term means growing gradually louder?",
                     correct: "Crescendo", wrong: ["Staccato", "Diminuendo", "Legato"],
                     slot: 1, .screen, 3),
        packQuestion("scr-27", "Who directed \"Psycho\" and \"Vertigo\"?",
                     correct: "Alfred Hitchcock", wrong: ["Stanley Kubrick", "Orson Welles", "Billy Wilder"],
                     slot: 2, .screen, 3),
        packQuestion("scr-28", "What was Charlie Chaplin's famous screen persona?",
                     correct: "The Tramp", wrong: ["The Kid", "The Clown", "The Drifter"],
                     slot: 3, .screen, 3),
    ]
}
