// Geography — 28 questions (10 warm, 10 medium, 8 hard).
// Correct slots cycle 0→1→2→3 to keep direction balance exact.
import Foundation

enum PackGeography {
    static let questions: [Question] = [
        // Difficulty 1 — warm-ups
        packQuestion("geo-01", "What is the largest ocean?",
                     correct: "The Pacific", wrong: ["The Atlantic", "The Indian", "The Arctic"],
                     slot: 0, .geography, 1),
        packQuestion("geo-02", "Which country is shaped like a boot?",
                     correct: "Italy", wrong: ["Spain", "Greece", "Portugal"],
                     slot: 1, .geography, 1),
        packQuestion("geo-03", "What is the capital of France?",
                     correct: "Paris", wrong: ["Lyon", "Marseille", "Nice"],
                     slot: 2, .geography, 1),
        packQuestion("geo-04", "The Sahara Desert is on which continent?",
                     correct: "Africa", wrong: ["Asia", "Australia", "South America"],
                     slot: 3, .geography, 1),
        packQuestion("geo-05", "What is the longest river in Africa?",
                     correct: "The Nile", wrong: ["The Congo", "The Zambezi", "The Niger"],
                     slot: 0, .geography, 1),
        packQuestion("geo-06", "Which country's flag shows a red maple leaf?",
                     correct: "Canada", wrong: ["Sweden", "Austria", "New Zealand"],
                     slot: 1, .geography, 1),
        packQuestion("geo-07", "What is the largest continent?",
                     correct: "Asia", wrong: ["Africa", "Europe", "North America"],
                     slot: 2, .geography, 1),
        packQuestion("geo-08", "Which city is home to the Statue of Liberty?",
                     correct: "New York", wrong: ["Washington", "Boston", "Philadelphia"],
                     slot: 3, .geography, 1),
        packQuestion("geo-09", "What is the capital of Japan?",
                     correct: "Tokyo", wrong: ["Osaka", "Kyoto", "Nagoya"],
                     slot: 0, .geography, 1),
        packQuestion("geo-10", "Russia spans which two continents?",
                     correct: "Europe and Asia", wrong: ["Only Asia", "Only Europe", "Europe and Africa"],
                     slot: 1, .geography, 1),

        // Difficulty 2
        packQuestion("geo-11", "What is the smallest country in the world?",
                     correct: "Vatican City", wrong: ["Monaco", "San Marino", "Liechtenstein"],
                     slot: 2, .geography, 2),
        packQuestion("geo-12", "What is the largest hot desert?",
                     correct: "The Sahara", wrong: ["The Gobi", "The Kalahari", "The Mojave"],
                     slot: 3, .geography, 2),
        packQuestion("geo-13", "What is the capital of Australia?",
                     correct: "Canberra", wrong: ["Sydney", "Melbourne", "Perth"],
                     slot: 0, .geography, 2),
        packQuestion("geo-14", "Which river flows through Paris?",
                     correct: "The Seine", wrong: ["The Loire", "The Rhone", "The Danube"],
                     slot: 1, .geography, 2),
        packQuestion("geo-15", "What is the tallest mountain above sea level?",
                     correct: "Everest", wrong: ["K2", "Kilimanjaro", "Denali"],
                     slot: 2, .geography, 2),
        packQuestion("geo-16", "Which country has the largest population?",
                     correct: "India", wrong: ["China", "USA", "Indonesia"],
                     slot: 3, .geography, 2),
        packQuestion("geo-17", "What is the capital of Canada?",
                     correct: "Ottawa", wrong: ["Toronto", "Vancouver", "Montreal"],
                     slot: 0, .geography, 2),
        packQuestion("geo-18", "Which country was once called Abyssinia?",
                     correct: "Ethiopia", wrong: ["Egypt", "Sudan", "Kenya"],
                     slot: 1, .geography, 2),
        packQuestion("geo-19", "Which strait separates Spain from Morocco?",
                     correct: "Gibraltar", wrong: ["Bosporus", "Hormuz", "Dover"],
                     slot: 2, .geography, 2),
        packQuestion("geo-20", "How many states make up the USA?",
                     correct: "Fifty", wrong: ["Forty-eight", "Fifty-one", "Fifty-two"],
                     slot: 3, .geography, 2),

        // Difficulty 3
        packQuestion("geo-21", "Where is the deepest point of the ocean?",
                     correct: "Mariana Trench", wrong: ["Java Trench", "Tonga Trench", "Puerto Rico Trench"],
                     slot: 0, .geography, 3),
        packQuestion("geo-22", "Which country spans the most time zones?",
                     correct: "France", wrong: ["Russia", "USA", "China"],
                     slot: 1, .geography, 3),
        packQuestion("geo-23", "What is the capital of New Zealand?",
                     correct: "Wellington", wrong: ["Auckland", "Christchurch", "Hamilton"],
                     slot: 2, .geography, 3),
        packQuestion("geo-24", "Which two countries share the longest border?",
                     correct: "USA and Canada", wrong: ["Russia and China", "Chile and Argentina", "USA and Mexico"],
                     slot: 3, .geography, 3),
        packQuestion("geo-25", "What is the driest non-polar desert?",
                     correct: "The Atacama", wrong: ["The Sahara", "The Gobi", "The Namib"],
                     slot: 0, .geography, 3),
        packQuestion("geo-26", "Which major city sits on two continents?",
                     correct: "Istanbul", wrong: ["Cairo", "Moscow", "Dubai"],
                     slot: 1, .geography, 3),
        packQuestion("geo-27", "What is the longest mountain range on land?",
                     correct: "The Andes", wrong: ["The Rockies", "The Himalayas", "The Alps"],
                     slot: 2, .geography, 3),
        packQuestion("geo-28", "Mount Kilimanjaro is in which country?",
                     correct: "Tanzania", wrong: ["Kenya", "Uganda", "Ethiopia"],
                     slot: 3, .geography, 3),
    ]
}
