// Science & nature — 32 questions (12 warm, 12 medium, 8 hard).
// Correct slots cycle 0→1→2→3 to keep direction balance exact.
import Foundation

enum PackScience {
    static let questions: [Question] = [
        // Difficulty 1 — warm-ups
        packQuestion("sci-01", "Which planet is known as the Red Planet?",
                     correct: "Mars", wrong: ["Venus", "Jupiter", "Mercury"],
                     slot: 0, .science, 1),
        packQuestion("sci-02", "Which gas do humans need to breathe in?",
                     correct: "Oxygen", wrong: ["Carbon dioxide", "Helium", "Hydrogen"],
                     slot: 1, .science, 1),
        packQuestion("sci-03", "How many planets are in our Solar System?",
                     correct: "Eight", wrong: ["Seven", "Nine", "Ten"],
                     slot: 2, .science, 1),
        packQuestion("sci-04", "Which force pulls a dropped apple to the ground?",
                     correct: "Gravity", wrong: ["Magnetism", "Friction", "Static"],
                     slot: 3, .science, 1),
        packQuestion("sci-05", "What is H2O better known as?",
                     correct: "Water", wrong: ["Hydrogen", "Table salt", "Rust"],
                     slot: 0, .science, 1),
        packQuestion("sci-06", "What is the largest animal ever known to live?",
                     correct: "Blue whale", wrong: ["African elephant", "Giant squid", "T. rex"],
                     slot: 1, .science, 1),
        packQuestion("sci-07", "At what Celsius temperature does water freeze?",
                     correct: "Zero", wrong: ["Ten", "Minus ten", "Five"],
                     slot: 2, .science, 1),
        packQuestion("sci-08", "Which organ pumps blood around the body?",
                     correct: "The heart", wrong: ["The liver", "The lungs", "The kidneys"],
                     slot: 3, .science, 1),
        packQuestion("sci-09", "Which star sits at the center of our Solar System?",
                     correct: "The Sun", wrong: ["Polaris", "Sirius", "The Moon"],
                     slot: 0, .science, 1),
        packQuestion("sci-10", "Which of these animals is a mammal?",
                     correct: "Dolphin", wrong: ["Shark", "Penguin", "Crocodile"],
                     slot: 1, .science, 1),
        packQuestion("sci-11", "What do caterpillars become?",
                     correct: "Butterflies", wrong: ["Beetles", "Dragonflies", "Grasshoppers"],
                     slot: 2, .science, 1),
        packQuestion("sci-12", "How many legs does an insect have?",
                     correct: "Six", wrong: ["Four", "Eight", "Ten"],
                     slot: 3, .science, 1),

        // Difficulty 2
        packQuestion("sci-13", "What is the chemical symbol for gold?",
                     correct: "Au", wrong: ["Ag", "Go", "Gd"],
                     slot: 0, .science, 2),
        packQuestion("sci-14", "Which planet has the most known moons?",
                     correct: "Saturn", wrong: ["Jupiter", "Neptune", "Mars"],
                     slot: 1, .science, 2),
        packQuestion("sci-15", "Which part of the cell holds its DNA?",
                     correct: "The nucleus", wrong: ["The membrane", "The cytoplasm", "The ribosome"],
                     slot: 2, .science, 2),
        packQuestion("sci-16", "Roughly how fast does light travel?",
                     correct: "300,000 km/s", wrong: ["30,000 km/s", "3,000 km/s", "3 million km/s"],
                     slot: 3, .science, 2),
        packQuestion("sci-17", "Which gas makes up most of Earth's atmosphere?",
                     correct: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Argon"],
                     slot: 0, .science, 2),
        packQuestion("sci-18", "What is the hardest natural substance?",
                     correct: "Diamond", wrong: ["Granite", "Titanium", "Quartz"],
                     slot: 1, .science, 2),
        packQuestion("sci-19", "How long does Earth take to orbit the Sun?",
                     correct: "About 365 days", wrong: ["About 30 days", "About 24 hours", "About 180 days"],
                     slot: 2, .science, 2),
        packQuestion("sci-20", "Which blood cells fight infection?",
                     correct: "White cells", wrong: ["Red cells", "Platelets", "Stem cells"],
                     slot: 3, .science, 2),
        packQuestion("sci-21", "What is the largest planet in the Solar System?",
                     correct: "Jupiter", wrong: ["Saturn", "Neptune", "Earth"],
                     slot: 0, .science, 2),
        packQuestion("sci-22", "Which metal has the chemical symbol Fe?",
                     correct: "Iron", wrong: ["Lead", "Tin", "Zinc"],
                     slot: 1, .science, 2),
        packQuestion("sci-23", "What type of animal is a Komodo dragon?",
                     correct: "A lizard", wrong: ["A snake", "A crocodile", "A salamander"],
                     slot: 2, .science, 2),
        packQuestion("sci-24", "What do fish use to breathe underwater?",
                     correct: "Gills", wrong: ["Lungs", "Fins", "Scales"],
                     slot: 3, .science, 2),

        // Difficulty 3
        packQuestion("sci-25", "On which planet is a day longer than its year?",
                     correct: "Venus", wrong: ["Mercury", "Mars", "Neptune"],
                     slot: 0, .science, 3),
        packQuestion("sci-26", "What is the most abundant element in the universe?",
                     correct: "Hydrogen", wrong: ["Helium", "Oxygen", "Carbon"],
                     slot: 1, .science, 3),
        packQuestion("sci-27", "Which element has atomic number 6?",
                     correct: "Carbon", wrong: ["Oxygen", "Nitrogen", "Boron"],
                     slot: 2, .science, 3),
        packQuestion("sci-28", "What is absolute zero, roughly, in Celsius?",
                     correct: "-273°C", wrong: ["-100°C", "-373°C", "-173°C"],
                     slot: 3, .science, 3),
        packQuestion("sci-29", "Which animal has three hearts?",
                     correct: "The octopus", wrong: ["The starfish", "The jellyfish", "The seahorse"],
                     slot: 0, .science, 3),
        packQuestion("sci-30", "Which planet spins almost on its side?",
                     correct: "Uranus", wrong: ["Neptune", "Mercury", "Pluto"],
                     slot: 1, .science, 3),
        packQuestion("sci-31", "What is the study of fungi called?",
                     correct: "Mycology", wrong: ["Botany", "Ecology", "Zoology"],
                     slot: 2, .science, 3),
        packQuestion("sci-32", "What is the smallest bone in the human body?",
                     correct: "The stapes", wrong: ["The ulna", "The coccyx", "The patella"],
                     slot: 3, .science, 3),
    ]
}
