// Words & language — 28 questions (10 warm, 10 medium, 8 hard).
// Correct slots cycle 0→1→2→3 to keep direction balance exact.
import Foundation

enum PackWords {
    static let questions: [Question] = [
        // Difficulty 1 — warm-ups
        packQuestion("wrd-01", "What is the opposite of \"ancient\"?",
                     correct: "Modern", wrong: ["Old", "Antique", "Historic"],
                     slot: 0, .words, 1),
        packQuestion("wrd-02", "What is a baby dog called?",
                     correct: "A puppy", wrong: ["A kitten", "A cub", "A foal"],
                     slot: 1, .words, 1),
        packQuestion("wrd-03", "What is the plural of \"mouse\" (the animal)?",
                     correct: "Mice", wrong: ["Mouses", "Meese", "Mouse"],
                     slot: 2, .words, 1),
        packQuestion("wrd-04", "Which of these letters is a vowel?",
                     correct: "E", wrong: ["B", "C", "D"],
                     slot: 3, .words, 1),
        packQuestion("wrd-05", "Which word sounds the same as \"flour\"?",
                     correct: "Flower", wrong: ["Floor", "Flare", "Flair"],
                     slot: 0, .words, 1),
        packQuestion("wrd-06", "Which word means the same as \"happy\"?",
                     correct: "Joyful", wrong: ["Weary", "Anxious", "Solemn"],
                     slot: 1, .words, 1),
        packQuestion("wrd-07", "What is the opposite of \"victory\"?",
                     correct: "Defeat", wrong: ["Triumph", "Battle", "Retreat"],
                     slot: 2, .words, 1),
        packQuestion("wrd-08", "Which animal's baby is called a kitten?",
                     correct: "The cat", wrong: ["The dog", "The horse", "The sheep"],
                     slot: 3, .words, 1),
        packQuestion("wrd-09", "What is the first letter of the Greek alphabet?",
                     correct: "Alpha", wrong: ["Beta", "Omega", "Delta"],
                     slot: 0, .words, 1),
        packQuestion("wrd-10", "Which word means \"very large\"?",
                     correct: "Enormous", wrong: ["Tiny", "Narrow", "Brief"],
                     slot: 1, .words, 1),

        // Difficulty 2
        packQuestion("wrd-11", "What do you call a word that reads the same backward?",
                     correct: "A palindrome", wrong: ["An anagram", "A homonym", "An acronym"],
                     slot: 2, .words, 2),
        packQuestion("wrd-12", "Which spelling is correct?",
                     correct: "Necessary", wrong: ["Neccessary", "Necessery", "Neccesary"],
                     slot: 3, .words, 2),
        packQuestion("wrd-13", "What is a group of crows called?",
                     correct: "A murder", wrong: ["A gaggle", "A parliament", "A swarm"],
                     slot: 0, .words, 2),
        packQuestion("wrd-14", "What does \"carpe diem\" mean?",
                     correct: "Seize the day", wrong: ["Buyer beware", "Time flies", "After the fact"],
                     slot: 1, .words, 2),
        packQuestion("wrd-15", "What is the last letter of the Greek alphabet?",
                     correct: "Omega", wrong: ["Zeta", "Sigma", "Psi"],
                     slot: 2, .words, 2),
        packQuestion("wrd-16", "Which word means the same as \"arid\"?",
                     correct: "Dry", wrong: ["Cold", "Fertile", "Windy"],
                     slot: 3, .words, 2),
        packQuestion("wrd-17", "What can a bilingual person do?",
                     correct: "Speak two languages", wrong: ["Read music", "Write with both hands", "See in the dark"],
                     slot: 0, .words, 2),
        packQuestion("wrd-18", "What is the opposite of \"expand\"?",
                     correct: "Contract", wrong: ["Extend", "Inflate", "Stretch"],
                     slot: 1, .words, 2),
        packQuestion("wrd-19", "What is the fear of spiders called?",
                     correct: "Arachnophobia", wrong: ["Agoraphobia", "Acrophobia", "Xenophobia"],
                     slot: 2, .words, 2),
        packQuestion("wrd-20", "Which word means \"happening every year\"?",
                     correct: "Annual", wrong: ["Monthly", "Constant", "Eternal"],
                     slot: 3, .words, 2),

        // Difficulty 3
        packQuestion("wrd-21", "What does \"gregarious\" mean?",
                     correct: "Sociable", wrong: ["Greedy", "Suspicious", "Clumsy"],
                     slot: 0, .words, 3),
        packQuestion("wrd-22", "How many lines does a sonnet have?",
                     correct: "Fourteen", wrong: ["Ten", "Twelve", "Sixteen"],
                     slot: 1, .words, 3),
        packQuestion("wrd-23", "What does \"ephemeral\" mean?",
                     correct: "Short-lived", wrong: ["Everlasting", "Invisible", "Fragile"],
                     slot: 2, .words, 3),
        packQuestion("wrd-24", "Which language gave English \"kindergarten\"?",
                     correct: "German", wrong: ["Dutch", "Danish", "Swedish"],
                     slot: 3, .words, 3),
        packQuestion("wrd-25", "What does the prefix \"hypo-\" mean?",
                     correct: "Under", wrong: ["Over", "Around", "Against"],
                     slot: 0, .words, 3),
        packQuestion("wrd-26", "Words like \"buzz\" and \"hiss\" are examples of what?",
                     correct: "Onomatopoeia", wrong: ["Alliteration", "Hyperbole", "Oxymoron"],
                     slot: 1, .words, 3),
        packQuestion("wrd-27", "What does \"ubiquitous\" mean?",
                     correct: "Found everywhere", wrong: ["Extremely rare", "Ancient", "Uninvited"],
                     slot: 2, .words, 3),
        packQuestion("wrd-28", "What does \"verbose\" mean?",
                     correct: "Wordy", wrong: ["Loud", "Angry", "Truthful"],
                     slot: 3, .words, 3),
    ]
}
